src/StockControl/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView 

urlpatterns = [
    path('', TemplateView.as_view(template_name="inicio/inicio.html"), name='inicio'),
    path('admin/', admin.site.urls),
    path('compras/', include('compra.urls', namespace='compra')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/compra/urls.py
from django.urls import path
from .views import ProveedoresListView, ProductosListView, ProductoCreateView, ProveedoreCreateView

app_name = 'compra'
# Se definen las sub-rutas de la app y su conexión con las vistas.
urlpatterns = [
    path('proveedores/listado/', ProveedoresListView.as_view(), name='proveedores_list'),
    path('productos/listado/', ProductosListView.as_view(), name='productos_list'),
    path('productos/crear/', ProductoCreateView.as_view(), name='productos_create'),
    path('proveedores/crear/', ProveedoreCreateView.as_view(), name='proveedores_create'),   
]

src/compra/models.py
from django.db import models

# Create your models here.
class Proveedor(models.Model):          
    """Clase que representa a los proveedores de los productos """
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    dni = models.BigIntegerField()        # Para no preocuparnos si se escala con los números

    def __str__(self):   #Método especial que devuelve una representación String de la instancia de la clase.
        return F"Nombre: {self.nombre.upper()} - Apellido: {self.apellido.upper()} - DNI: {self.dni}"

class Producto(models.Model):           
    """ Clase que representa a los productos """
    nombre = models.CharField(max_length=50)
    precio = models.FloatField()
    stock_actual = models.IntegerField()
    foto = models.ImageField(upload_to='productos_img/', default='producto_default.png')
    proveedor = models.ForeignKey(Proveedor, on_delete=models.PROTECT)  #No permite eliminar un proveedor si no se eliminan o modifican los productos que lo referencian.

    def __str__(self):
        return F"Nombre: {self.nombre.upper()} - Precio: {self.precio} - Stock: {self.stock_actual} - Proveedor: {self.proveedor.nombre} {self.proveedor.apellido}"
    
    

src/compra/views.py
from django.urls import reverse_lazy
from django.views import generic
from .models import Proveedor, Producto
from django.views.generic.edit import CreateView

# Create your views here.

class ProveedoresListView(generic.ListView):            # Vista basada en clases para listar proveedores.
    queryset = Proveedor.objects.all()
    template_name = "proveedores/proveedores_list.html"
    context_object_name = 'lista_de_proveedores'

class ProveedoreCreateView(CreateView):
    model = Proveedor                                   # Vista basada en clases para crear un proveedor.
    fields = ['nombre', 'apellido', 'dni']              # Campos que se envían a la plantilla.
    template_name = "proveedores/proveedores_create.html"
    success_url = reverse_lazy('compra:proveedores_list')

class ProductosListView(generic.ListView):              # Vista basada en clases para listar productos.
    queryset = Producto.objects.all()
    template_name = "productos/productos_list.html"
    context_object_name = 'lista_de_productos'

class ProductoCreateView(CreateView):                   # Vista basada en clases para crear un producto.
    model = Producto
    fields = ['nombre', 'precio', 'stock_actual', 'foto', 'proveedor']
    template_name = "productos/productos_create.html"
    success_url = reverse_lazy('compra:productos_list')

src/templates/base.html
{% load static %}       <!-- Carga las etiquetas estáticas de Django definiendo static (su ruta)-->
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="{% static '/img/favicon.ico' %}"> <!-- Utiliza la ruta relativa a static -->
    <title>StockControl</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg bg-dark border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
          <img src={% static '/img/logo-inicio.jpg' %} class="ms-4" alt="Imagen de inicio.">
          <a class="navbar-brand ms-1" href="{% url 'inicio' %}">StockControl</a>   
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent" >
            <ul class="navbar-nav ms-auto me-5 pe-5 mb-2 mb-lg-0">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Menu
                </a>
                <ul class="dropdown-menu">    <!-- url permite generar dinámicamente enlaces referenciando un path de urls.py -->
                  <li><a class="dropdown-item" href="{% url 'compra:proveedores_list' %}">Listado de Proveedores</a></li>
                  <li><a class="dropdown-item" href="{% url 'compra:productos_list' %}">Listado de Productos</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'compra:proveedores_create' %}">Agregar Proveedor</a></li>
                  <li><a class="dropdown-item" href="{% url 'compra:productos_create' %}">Agregar Producto</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'admin:index' %}">Administrador</a></li>
                </ul>
              </li>              
            </ul>
          </div>
        </div>
      </nav>      
      {% block content %}     <!-- Aqui se insertan las demás plantillas que extienden a base.html -->
      {% endblock content %}
      <footer class="bg-dark text-white py-3 my-4">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <p class="mb-0 ms-4">© 2024 Pablo Alexis König. Todos los derechos reservados.</p>
            </div>
            <div class="col-md-6 text-md-right">
              <a href="https://www.linkedin.com/in/pablo-alexis-konig/" target="_blank" class="imagen-derecha me-4">
                <img src="{% static '/img/linkedin.png' %}" alt="LinkedIn" width="30" height="30">
              </a>
              <a href="https://github.com/PabloKonig/Proyecto-final-Python-Django-Alkemy/tree/main" target="_blank" class="imagen-derecha me-4">
                <img src="{% static '/img/github.png' %}" alt="GitHub" width="30" height="30">
              </a>
            </div>
          </div>
        </div>
      </footer>
    </div>    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
  <style>
    .alineado-derecha {
      text-align: right;
    }
    .imagen-derecha {
      float: right;
    }
  </style>
</html>

src/templates/inicio/inicio.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h1 class="text-center mx-auto p-2 m-4">StockControl</h1>
<img src={% static '/img/inicio.jpg' %} class="rounded mx-auto d-block" alt="Imagen de inicio.">
{% endblock content %}

src/templates/productos/productos_create.html
{% extends "base.html" %}

{% block content %}
<h2 class="my-4">Agregar producto</h2>
<section class="alert alert-warning" role="alert">
    <form method="post" enctype="multipart/form-data">  <!-- multipart/form-data para poder subir la imagen. --> 
        {% csrf_token %}
        <table class="table table-dark table-striped">
            <tr>
                <td>Nombre: </td>
                <td>{{form.nombre}}</td>
            </tr>
            <tr>
                <td>Precio: </td>
                <td>{{form.precio}}</td>                
            </tr>
            <tr>
                <td>Stock actual: </td>
                <td>{{form.stock_actual}}</td>                
            </tr>
            <tr>
                <td>Foto: </td>
                <td>{{form.foto}}</td>                
            </tr>
            <tr>
                <td>Stock actual: </td>
                <td>{{form.proveedor}}</td>                
            </tr>
        </table>
        <button type="submit" class="btn btn-outline-primary">Guardar</button>
        <a class="btn btn-outline-primary m-3" href="{% url 'inicio' %}" role="button">Inicio</a>
    </form>
</section> 
{% endblock content %}

src/templates/productos/productos_list.html
{% extends "base.html" %} # Se toma como base el archivo base.html y se inserta el bloque
{% block content %}
<h2 class="my-4">Listado de productos</h2>
    <table class="table table-hover">
        <thead class="table-secondary">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Foto</th>
                <th scope="col">Nombre</th>
                <th scope="col" class="alineado-derecha">Precio</th>
                <th scope="col" class="alineado-derecha">Stock</th>
                <th scope="col" class="alineado-derecha">Proveedor</th>
            </tr>
        </thead>
        <tbody>
            {% for producto in lista_de_productos %}
            <tr height="70px">
                <td scope="row">{{producto.id}}</td>
                <td scope="row"> <img src="{{ producto.foto.url }}" width="50px" max-height="50px"/></td>
                <td>{{producto.nombre}}</td> 
                <td class="alineado-derecha">{{producto.precio}}</td> 
                <td class="alineado-derecha">{{producto.stock_actual}}</td>
                <td class="alineado-derecha">{{producto.proveedor.nombre}} {{producto.proveedor.apellido}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-outline-primary m-3" href="{% url 'compra:productos_create' %}" role="button">Agregar producto</a>
    <a class="btn btn-outline-primary m-3" href="{% url 'inicio' %}" role="button">Inicio</a>
{% endblock content %}

src/templates/proveedores/proveedores_create.html
{% extends "base.html" %}
{% block content %}
<h2 class="my-4">Agregar producto</h2>
<section class="alert alert-warning" role="alert">
    <form method="post">
        {% csrf_token %}
        <table class="table table-dark table-striped">
            <tr>
                <td>Nombre</td>
                <td>{{form.nombre}}</td>
            </tr>
            <tr>
                <td>Apellido</td>
                <td>{{form.apellido}}</td>                
            </tr>
            <tr>
                <td>DNI</td>
                <td>{{form.dni}}</td>                
            </tr>
        </table>
        <button type="submit" class="btn btn-outline-primary">Guardar</button>
        <a class="btn btn-outline-primary m-3" href="{% url 'inicio' %}" role="button">Inicio</a>
    </form>
</section> 
{% endblock content %}

src/templates/proveedores/proveedores_list.html
{% extends "base.html" %}

{% block content %}
<h2 class="my-4">Listado de proveedores</h2>
    <table class="table table-hover">
        <thead class="table-secondary">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Nombre</th>
                <th scope="col">Apellido</th>
                <th scope="col">DNI</th>
            </tr>
        </thead>
        <tbody>
            {% for proveedor in lista_de_proveedores %}
            <tr>
                <td>{{proveedor.id}}</td> 
                <td>{{proveedor.nombre}}</td> 
                <td>{{proveedor.apellido}}</td>
                <td>{{proveedor.dni}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-outline-primary m-3" href="{% url 'compra:proveedores_create' %}" role="button">Agregar proveedor</a>
    <a class="btn btn-outline-primary m-3" href="{% url 'inicio' %}" role="button">Inicio</a>
{% endblock content %}
        